# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

# Box / OS
VAGRANT_BOX = "debian/buster64"

# User VM
VM_USER = 'PlasticDuck'

# Machine Name
VM_NAME = 'PoolyMachine'

Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = VAGRANT_BOX

  config.vm.hostname = VM_NAME

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  config.vbguest.auto_update = false
  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = false
    vb.name = VM_NAME
  
    # Customize the amount of memory on the VM:
    vb.memory = "2048"
  end

  # Installation des Dépendances
  config.vm.provision "shell", path: "./provision/update.sh"
  config.vm.provision "shell", path: "./provision/gcc_recipe.sh"
  config.vm.provision "shell", path: "./provision/git.sh"
end
